// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7afAkVCzo88tbmvTjeo08Ry7u-dHZToA',
    appId: '1:600187168194:web:805d088af5f41dccb2a25b',
    messagingSenderId: '600187168194',
    projectId: 'apphuevoslagranja',
    authDomain: 'apphuevoslagranja.firebaseapp.com',
    storageBucket: 'apphuevoslagranja.appspot.com',
    measurementId: 'G-J653DJP2YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bZT6h3FsIdcEVtncBVjoJhKmoQRiM0E',
    appId: '1:600187168194:android:35e4e7331c13fb0bb2a25b',
    messagingSenderId: '600187168194',
    projectId: 'apphuevoslagranja',
    storageBucket: 'apphuevoslagranja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHRo23w2EVtRZN29591l1hWWCgIuekeQ',
    appId: '1:600187168194:ios:2de064c40c03e795b2a25b',
    messagingSenderId: '600187168194',
    projectId: 'apphuevoslagranja',
    storageBucket: 'apphuevoslagranja.appspot.com',
    iosClientId: '600187168194-48ld08fkuabvt785u1t6jt7nmo0aqqr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.huevosLaGranja',
  );
}
